-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 20:50:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`book_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `id` INT NOT NULL,
  `author` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `description` BLOB NULL,
  `book_type_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn_number_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `fk_books_book_type1_idx` (`book_type_id` ASC) VISIBLE,
  INDEX `fk_books_author1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_book_type1`
    FOREIGN KEY (`book_type_id`)
    REFERENCES `mydb`.`book_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `uesrname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book_copies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book_copies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `books_id` INT(10) NOT NULL,
  `owner_id` INT NOT NULL,
  `borrower_id` INT NULL,
  `issue_date` DATETIME NULL,
  `return_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_copies_books_idx` (`books_id` ASC) VISIBLE,
  INDEX `fk_book_copies_member1_idx` (`owner_id` ASC) VISIBLE,
  INDEX `fk_book_copies_member2_idx` (`borrower_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_copies_books`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_copies_member1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_copies_member2`
    FOREIGN KEY (`borrower_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prferences` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_preferances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_preferances` (
  `id` INT NOT NULL,
  `prferences_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_preferances_prferences1_idx` (`prferences_id` ASC) VISIBLE,
  INDEX `fk_member_preferances_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_preferances_prferences1`
    FOREIGN KEY (`prferences_id`)
    REFERENCES `mydb`.`prferences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_preferances_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
